repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: ["-style=file"]
      - id: cpplint
        args: ["--filter=-build/c++11,-build/namespace,-readability/namespace,-whitespace/braces,-whitespace/indent,-whitespace/line_length,-whitespace/newline,-whitespace/semicolon", --verbose=0]
      #- id: clang-tidy
      #  args: [-p=build_linux, -checks=*, -warnings-as-errors=*]
      #- id: uncrustify
      - id: cppcheck
        args: [--language=c++, --std=c++11, --library=googletest, --inline-suppr, --enable=all]
