repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
  #    - id: check-added-large-files
  #    - id: check-ast
  #    - id: check-case-conflict
  #    - id: check-executables-have-shebangs
  #    - id: check-shebang-scripts-are-executable
  #    - id: debug-statements
  #    - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
  #    - id: requirements-txt-fixer
  #    - id: trailing-whitespace
  #- repo: https://github.com/pocc/pre-commit-hooks
  #  rev: v1.3.5
  #  hooks:
  #    - id: clang-format
  #      args: [-i]
      #- id: cppcheck
      #  args: [--language=c++, --std=c++11, --library=googletest, --inline-suppr, --enable=all]
      #- id: cpplint
      #  args: ['--filter=-build/c++11,-build/namespace,-readability/namespace,-readability/nolint,-whitespace/braces,-whitespace/indent,-whitespace/line_length,-whitespace/newline,-whitespace/semicolon']
      #- id: clang-tidy
      #  entry: scripts/pocc-shim.py
