name: Build and Test

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  Build-and-Test_Ubuntu:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        build_type:
          - Debug
          - Release
    steps:
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.15'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        make -j
    - name: Run unit tests
      run: |
        build/UnitTest/UnitTest

  build-and-test_Windows:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type:
          - Debug
          - Release
    steps:
    - name: Install Developer Command Prompt for VS
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.15'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        mkdir build && cd build
        cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        nmake
    - name: Run unit tests
      run: |
        build/UnitTest/UnitTest
